version: '3.6'

services:
  proxy:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/traefik.toml:/etc/traefik/traefik.toml:ro
      - ../config/acme.json:/acme.json
    networks:
      default:
        aliases:
          - api.hybridmoney.exchange
          - auth.hybridmoney.exchange
          - ws.ranger.hybridmoney.exchange
          - pma.hybridmoney.exchange
          - eth.hybridmoney.exchange
          - monitor.hybridmoney.exchange
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: monitor.hybridmoney.exchange'
      traefik.port: 8080
